/**
 * @authors ZiQiangWang
 * @email   814120507@qq.com
 * @date    2017-07-28 15:13:19
 */

// auth
export const LOSE_AUTH = 'LOSE_AUTH';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILUARE = 'LOGOUT_FAILUARE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// article
export const RESET_EDITOR = 'RESET_EDITOR';

export const SHOW_ARTICLE_LIST = 'SHOW_ARTICLE_LIST';

export const ARTICLE_CHANGE = 'ARTICLE_CHANGE';

export const ARTICLE_SWITCH = 'ARTICLE_SWITCH';

export const ARTICLE_LIST_REQUEST = 'ARTICLE_LIST_REQUEST';
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS';
export const ARTICLE_LIST_FAILURE = 'ARTICLE_LIST_FAILURE';

export const ARTICLE_DETAIL_REQUEST = 'ARTICLE_DETAIL_REQUEST';
export const ARTICLE_DETAIL_SUCCESS = 'ARTICLE_DETAIL_SUCCESS';
export const ARTICLE_DETAIL_FAILURE = 'ARTICLE_DETAIL_FAILURE';

export const ADD_ARTICLE_REQUEST = 'ADD_ARTICLE_REQUEST';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_FAILURE = 'ADD_ARTICLE_FAILURE';

export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_FAILURE = 'UPDATE_ARTICLE_FAILURE';

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE';


export const EDIT_OR_PREVIEW = 'EDIT_OR_PREVIEW';
export const SHOW_EDITOR_NAV = 'SHOW_EDITOR_NAV';
export const SPLIT_MODE = 'SPLIT_MODE';
export const CHANGE_ORDER = 'CHANGE_ORDER';
export const FULLSCREEN_MODE = 'FULLSCREEN_MODE';


export const PAGE_ARTICLE_REQUEST = 'PAGE_ARTICLE_REQUEST';
export const PAGE_ARTICLE_SUCCESS = 'PAGE_ARTICLE_SUCCESS';
export const PAGE_ARTICLE_FAILURE = 'PAGE_ARTICLE_FAILURE';

// Blog
export const START_BLOG = 'START_BLOG';

export const BLOG_DETAIL_REQUEST = 'BLOG_DETAIL_REQUEST';
export const BLOG_DETAIL_SUCCESS = 'BLOG_DETAIL_SUCCESS';
export const BLOG_DETAIL_FAILURE = 'BLOG_DETAIL_FAILURE';
